using System.Security.Cryptography;
using System.Text;
using CSharpFunctionalExtensions;

namespace DiceToSeed.Core;

/// <summary>
/// Everything the backup key mode puts on screen. As with <see cref="SeedDerivation"/>, the
/// intermediate values are shown rather than just the answer, because another implementation
/// gets compared against them and a tool that shows only the result cannot say which step
/// disagreed.
/// </summary>
public sealed record BackupKeyDerivation(
    string Preimage,
    string KeyHex,
    string CheckCode)
{
    /// <summary>
    /// The key split into groups of four characters, for transcription. Sixty-four unbroken hex
    /// characters is where people lose their place, and a grouped rendering also makes it
    /// possible to resume after an interruption by counting groups rather than characters.
    ///
    /// This lives here rather than in the page because the tool receiving the key has to display
    /// it the same way for the two to be compared at a glance.
    /// </summary>
    public IReadOnlyList<string> KeyHexGroups =>
        Enumerable.Range(0, KeyHex.Length / 4)
            .Select(group => KeyHex.Substring(group * 4, 4))
            .ToList();
}

/// <summary>
/// The backup key, k: the 32-byte symmetric key that encrypts the backup payload and that
/// SLIP-39 then splits into shares. This mode exists so k can come off physical dice instead of
/// a generator whose output nobody can check, which is the same argument the seed mode rests on.
///
/// The convention is deliberately the one this app already uses, so nothing new has to be
/// trusted or published:
///
///   k = SHA-256(the roll digits, joined by nothing)
///
/// All 32 bytes, no truncation, because k is a 32-byte key. That makes it exactly the value the
/// seed mode already displays at step 2, and it stays reproducible with one shell command:
///
///   printf '%s' "$ROLLS" | sha256sum
///
/// Two rules are not enforceable here and belong to the caller and the documentation.
///
///   1. The roll log MUST be a fresh session, never the one used for a seed. On a 24-word seed
///      the BIP-39 entropy IS this hash, byte for byte, and on 12 words it is its first half. A
///      reused log therefore makes k identical to the wallet it is supposed to protect, and the
///      shares stop protecting anything. This app enforces it within a session by clearing the
///      roll log when the mode changes; the tool that consumes k enforces the rest, by comparing
///      k against the seed it was given.
///   2. Dice for k do not remove trust in a random number generator, and the UI must not claim
///      they do. The age file key is generated by the consuming tool's own RNG and the payload
///      is encrypted under that; k only wraps it. Dice give k a provenance you can account for,
///      which is worth having and is not the same claim.
/// </summary>
public static class BackupKey
{
    /// <summary>
    /// Sixteen bits of check. Enough that a transcription slip is caught rather than discovered
    /// at recovery, and not intended as anything else: it is a typo detector, not a security
    /// control, and it protects nothing against someone who can change the key.
    /// </summary>
    public const int CheckCodeLength = 4;

    /// <summary>
    /// Derives from a raw roll log, enforcing the same minimum the seed mode uses for the same
    /// entropy target. This is the entry point the UI uses.
    /// </summary>
    public static Result<BackupKeyDerivation> Derive(string rolls, EntropyStrength strength) =>
        DiceRolls.Read(rolls)
            .Bind(log => log.MeetsMinimumFor(strength).Map(() => log))
            .Map(FromLog);

    /// <summary>
    /// The same derivation with the length rule skipped, for tests that use short vectors.
    /// Internal for the same reason the seed mode's equivalent is: the check the UI applies
    /// cannot be reached past from outside this assembly.
    /// </summary>
    internal static Result<BackupKeyDerivation> DeriveIgnoringMinimum(string rolls) =>
        DiceRolls.Read(rolls).Map(FromLog);

    /// <summary>
    /// The check code: the first four characters of the lowercase hex SHA-256 of the lowercase
    /// hex key. It is computed over the printed string rather than over the key bytes on
    /// purpose, so that anyone can reproduce it from what is on screen with one command and no
    /// hex decoding step:
    ///
    ///   printf '%s' "$K_HEX" | sha256sum | cut -c1-4
    ///
    /// The consuming tool recomputes it from the key it was given and refuses on a mismatch.
    /// </summary>
    public static string CheckCodeFor(string keyHex) =>
        Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(keyHex)))[..CheckCodeLength];

    static BackupKeyDerivation FromLog(DiceRollLog log)
    {
        // ASCII by construction: the log is the digits 1 to 6. UTF-8 is stated rather than
        // assumed so the encoding is visible where bytes that become a key are produced.
        var keyHex = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(log.Preimage)));

        return new BackupKeyDerivation(log.Preimage, keyHex, CheckCodeFor(keyHex));
    }
}
